### ISSUE TITLE
Shared automation framework lib

### ISSUE THREAD

**Issue by timkimadobe** [adobe/aepsdk-edge-android#111]
### Epic description

Create an automation framework library that can be shared across multiple mobile extensions.
Depending on the evaluation result on type of utilities used across extensions, support can include integration tests framework including advanced JSON comparison system, functional tests and/or unit tests utilities.

Port over full set of APIs from iOS.

### Tasks

- [x] #105 
- [x] #110 
- [x] #107
- [x] https://github.com/adobe/aepsdk-testutils-android/issues/3
- [x] https://github.com/adobe/aepsdk-testutils-android/issues/2
- [x] https://github.com/adobe/aepsdk-testutils-android/issues/1
